name: CI - Feature Branch

on:
  push:
    branches-ignore:
    - main
    - dev
    - pre-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Validate and build Node services
      uses: ./.github/actions/node-validate-build
      with:
        node_version: '20'
